# NumPy
(Numeric Python)

### Installation

python -m pip install numpy

### فراخوانی

In [1]:
import numpy as np

In [3]:
np.__version__

'1.21.5'

### Arrays

In [4]:
a = np.array([1,4,5,8])
a

array([1, 4, 5, 8])

In [5]:
print(a)

[1 4 5 8]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
a = np.array([1.,4.,5.,8.])
a

array([1., 4., 5., 8.])

In [9]:
a.dtype

dtype('float64')

In [11]:
a = np.array([1,4,5,8],dtype='float')
a.dtype

dtype('float64')

عنصر سوم

In [12]:
a[2]

5.0

In [13]:
a[2:]

array([5., 8.])

In [14]:
a[:2]

array([1., 4.])

In [15]:
a[0] = 5.0

In [16]:
a

array([5., 4., 5., 8.])

تفاوت با لیست

In [17]:
b = [[1,2,3],[4,5,6]]

In [18]:
b[0][0]

1

In [19]:
a = np.array([[1,2,3],[4,5,6]])

In [20]:
a[0,0]

1

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6]])

زیرمجموعه

In [23]:
a[1,:]

array([4, 5, 6])

In [24]:
a[:,1]

array([2, 5])

###  shape

In [25]:
a.shape

(2, 3)

### len

In [26]:
len(a)

2

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a.dtype

dtype('int32')

In [29]:
2 in a

True

In [30]:
0 in a

False

### تغییر شکل آرایه‌های چند بعدی

In [31]:
a = np.array(range(10),dtype='float')

In [32]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
a.reshape((5,2))

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [34]:
a.shape

(10,)

In [35]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
a = a.reshape((5,2))
a.shape

(5, 2)

### دستور انتساب

In [37]:
a = np.array([1,2,3])

In [38]:
b = a

In [39]:
c = a.copy()

In [40]:
b[0] = 0
b

array([0, 2, 3])

In [41]:
a

array([0, 2, 3])

In [42]:
c

array([1, 2, 3])

### tolist

In [43]:
c.tolist()

[1, 2, 3]

### transpose

In [44]:
a = np.array(range(6)).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [46]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### flatten

In [47]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

تجمیع آرایه‌ها

In [49]:
a = np.array([1,2])

In [50]:
b = np.array([3,4,5,6])

In [51]:
c = np.array([7,8,9])

In [52]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [54]:
a


array([[1, 2],
       [3, 4]])

In [55]:
b

array([[5, 6],
       [7, 8]])

In [56]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [58]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

(2, 2, 2)

### newaxis

In [61]:
a = np.array([1,2,3])
a.shape

(3,)

In [62]:
a[:,np.newaxis].shape

(3, 1)

In [63]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [64]:
a[np.newaxis,:].shape

(1, 3)

In [65]:
a[np.newaxis,:]

array([[1, 2, 3]])