# numpy
## part 2

### آرایه‌های خاص

### arange

In [1]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
np.arange(1,6,2,dtype=float)

array([1., 3., 5.])

### zeros

In [5]:
np.zeros((2,3),dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

### ones

In [7]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

### zeros_like ones_like

In [8]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.shape

(2, 3)

In [10]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

### indentity

In [12]:
np.identity(4,dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### ریاضیات برداری

In [13]:
a = np.array([1,2,3])
b = np.array([5,2,6])

In [14]:
a + b

array([6, 4, 9])

In [15]:
a - b

array([-4,  0, -3])

In [16]:
a*b

array([ 5,  4, 18])

In [17]:
a/b

array([0.2, 1. , 0.5])

In [18]:
b**a

array([  5,   4, 216], dtype=int32)

In [19]:
a = np.array([[1,2],[3,4]])

In [20]:
b= np.array([[2,0],[1,3]])

In [21]:
a*b

array([[ 2,  0],
       [ 3, 12]])

### sin cos exp

In [22]:
a = np.array([1,4,9])

In [23]:
np.sqrt(a)

array([1., 2., 3.])

In [25]:
np.sqrt(9)

3.0

$\pi$

In [26]:
np.pi

3.141592653589793

e

In [27]:
np.e

2.718281828459045

### عملیات مقایسه بین بردارها

In [30]:
a = np.array([1,3,0])
b = np.array([0,3,2])

In [31]:
a>b

array([ True, False, False])

In [32]:
a==b

array([False,  True, False])

In [33]:
a>2

array([False,  True, False])

### where

In [34]:
a = np.array([1,3,0],dtype=float)

In [35]:
1/a

C:\Users\mojta\AppData\Local\Temp\ipykernel_6756\261954055.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/a


array([1.        , 0.33333333,        inf])

In [36]:
np.where(a!=0,1/a,a)

C:\Users\mojta\AppData\Local\Temp\ipykernel_6756\3020106849.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.where(a!=0,1/a,a)


array([1.        , 0.33333333, 0.        ])

In [37]:
np.where(a>0,3,2)

array([3, 3, 2])

### ریاضیات ماتریسی و برداری

### ضرب داخلی

In [38]:
a = np.array([1,2,3])
b = np.array([0,1,1])

In [39]:
a*b

array([0, 2, 3])

In [40]:
np.dot(a,b)

5

In [41]:
np.dot(b,a)

5

In [42]:
a = np.array([[0,1],[2,3]])

In [43]:
b = np.array([2,3]) 

In [44]:
c = np.array([[1,1],[4,0]]) 

In [45]:
np.dot(b,a)

array([ 6, 11])

In [46]:
b.shape

(2,)

In [47]:
np.dot(a,b)

array([ 3, 13])

In [48]:
b.reshape(2,1)

array([[2],
       [3]])

In [49]:
b.reshape(1,2)

array([[2, 3]])

In [50]:
b.reshape(-1,1)

array([[2],
       [3]])

In [51]:
b.reshape(1,-1)

array([[2, 3]])

### matmul

In [54]:
np.matmul(b.reshape(1,-1),a)

array([[ 6, 11]])

In [57]:
b.reshape(-1,1).shape

(2, 1)

In [58]:
np.matmul(a,b.reshape(-1,1))

array([[ 3],
       [13]])

### ضرب خارجی

In [59]:
a = np.array([1,4,0])

In [60]:
b = np.array([2,2,1]) 

In [61]:
np.cross(a,b)

array([ 4, -1, -6])

In [62]:
np.cross(b,a)

array([-4,  1,  6])

### linalg

In [63]:
a = np.array([[4,2,0],[9,3,7],[1,2,1]])
a

array([[4, 2, 0],
       [9, 3, 7],
       [1, 2, 1]])

In [64]:
np.linalg.det(a)

-48.00000000000003

In [65]:
np.linalg.inv(a)

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])