# scipy

### انتگرال گیری عددی

### quad
General purpose integration

In [1]:
import numpy as np
from scipy.integrate import quad

$I=\int_1^2 e^{-x^2} dx$

In [2]:
def f(x):
    return np.exp(-x**2)

In [3]:
quad(f,1,2)

(0.13525725794999466, 1.5016572202374808e-15)

In [4]:
I = quad(f,1,2)[0]

In [5]:
I

0.13525725794999466

In [6]:
I = quad(lambda x: np.exp(-x**2),1,2)[0]
I

0.13525725794999466

$I = \int_0^\infty e^{-x}dx$

In [9]:
I = quad(lambda x: np.exp(-x),0,np.inf)[0]

In [10]:
I

1.0000000000000002

###  انتگرال گیری دوگانه

### dblqud

$I= \int_{-\infty}^{+\infty}\int_{-\infty}^{+\infty} e^{-x^2-y^2}dxdy$

In [11]:
from scipy.integrate import dblquad

In [12]:
I = dblquad(lambda x,y: np.exp(-x**2-y**2),-np.inf,+np.inf,lambda x: -np.inf,lambda x:+np.inf)[0]

In [13]:
I

3.141592653589777

$I =  \int_0^\frac{1}{2}\int_0^{1-2y}xydxdy$

In [14]:
I = dblquad(lambda x,y: x*y, 0,1/2,lambda y:0 ,lambda y:1-2*y)[0]
I

0.010416666666666668

In [16]:
import sympy as sp
x,y = sp.symbols('x y')

In [17]:
sp.integrate(x*y,(x,0,1-2*y))

y*(1 - 2*y)**2/2

In [20]:
sp.integrate(sp.integrate(x*y,(x,0,1-2*y)),(y,0,sp.Rational(1,2))).evalf()

0.0104166666666667

### ریشه های صفر یک معادله غیر خطی

In [21]:
from scipy.optimize import newton

$x^3-1=0$

In [22]:
newton(lambda x: x**3-1,0.5)

0.9999999999999973

In [24]:
newton(lambda x: x**3-1,0.5,fprime=lambda x: 3*x**2)

1.0

### Polynimials

In [26]:
p = np.poly1d([3,4,5])

In [27]:
print(p)

   2
3 x + 4 x + 5


In [28]:
print(p*p)

   4      3      2
9 x + 24 x + 46 x + 40 x + 25


In [29]:
print(p+p)

   2
6 x + 8 x + 10


In [30]:
print(p.deriv())

 
6 x + 4


In [31]:
p.deriv()

poly1d([6, 4])

In [32]:
print(p.integ())

   3     2
1 x + 2 x + 5 x


In [33]:
print(p.integ(k=6))

   3     2
1 x + 2 x + 5 x + 6


In [34]:
print(p)

   2
3 x + 4 x + 5


In [35]:
p(2)

25

In [36]:
np.roots(p)

array([-0.66666667+1.1055416j, -0.66666667-1.1055416j])

In [37]:
check_board =[[1,0,1,0,1,0,1,0],
[0,1,0,1,0,1,0,1],
[0]*8,[0]*8,[0]*8,[0]*8,
[2,0,2,0,2,0,2,0],
[0,2,0,2,0,2,0,2]]

In [38]:
check_board

[[1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [2, 0, 2, 0, 2, 0, 2, 0],
 [0, 2, 0, 2, 0, 2, 0, 2]]

In [49]:
np.where(np.array(check_board)==2)

(array([6, 6, 6, 6, 7, 7, 7, 7], dtype=int64),
 array([0, 2, 4, 6, 1, 3, 5, 7], dtype=int64))